apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-a
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-a
    spec:
      containers:
        - image: example-image
          name: example-image
          resources: {}
status: {}
