apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-sender
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-sender
    spec:
      containers:
        - image: gcr.io/learning-357114/ms-sender:1.0.0
          name: ms-sender
          resources: {}
          imagePullPolicy: Always
status: {}
