# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-sender
  name: ms-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-sender
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-sender
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: ms-sender-pubsub-key
      containers:
        - image: gcr.io/learning-357114/ms-sender:1.0.0
          name: ms-sender
          resources: {}
          imagePullPolicy: Always
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/ms-sender-pubsub-credentials.json
status: {}
